Portafolio Milestone 2: Works Section
eroiyo/My-Portafolio pull request #2
Opened 2021-06-04 21:47 UTC by eroiyo

Add Works Section

--The work section includes a lot of templates of projects
--More fogs for the background
--More height

Add Projects Template
--Project Templates features
    *Image of the project
    *Description of the project
    *Button to display more information (coming soon)
    *Tags

2021-06-04 23:06 UTC, Shaher-11 requested changes
Hello @eroiyo,

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Please check the comments below for detailed feedback.
- [ ] Kindly test your project with the dev tools and make sure everything positioned properly 


## Optional Suggestions 💡
_The following point is highly recommended to boost your productivity , Please consider it 

- take advantage of the dev tools and make sure everything works properly on Samsung and iPhone devices.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-06-04 23:18 UTC, Shaher-11 commented on style.css
> +  left: 0;
If you are using chrome then right click on the page and choose  inspect then click on the devise icon,
this way you will be able to test on all devices or at least the common ones

2021-06-04 23:36 UTC, eroiyo commented on style.css
> +  left: 0;
Thanks you.

2021-06-05 02:03 UTC, eroiyo commented
Ok, prepared for other review!

Increased the spaces between name and title (the h1 and the h2)
Increased the spaces between project image and name
now the buttons use flex instead of absolute and now positioned properly
the work title are now 2 lines instead of one

2021-06-05 05:01 UTC, MahmoudBakr23 requested changes
Hi @eroiyo😃, 

Great work on making the changes requested by a previous reviewer 👏
Extra credit for the Live Demo Link 💯 Keep up the great work 👍 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **OPTIONAL**
Kindly check the MIT link in your README because it's broken.
Please keep in mind that such a small mistake might leave a bad impression on future viewers. So, I highly recommend fixing it.

- [ ] **OPTIONAL**
Please correct the misspelling in the PR headline "Portafolio". Instead, it's "Portfolio".
I recommend installing [Grammarly](https://app.grammarly.com/) to check for such mistakes while typing.

_Check the **OPTIONAL** comments under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 12:33 UTC, eroiyo commented
Sure, it's time for other review, I did some changes!

--Circles and fogs CSS effects are now gone, now we use 2 different images for the background
--Projects cards are now properly saved wrapped with list tags
--Bottom button is now properly displayed
--Font and typographic have been established, and a lot of redundant code was deleted

Thanks for the review

2021-06-05 12:43 UTC, smcommits approved these changes
### Status: Approved 👍🏽 

Hi @eroiyo, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-06-07 15:42 UTC, merged