Milestone 4 Desktop Support
eroiyo/My-Portafolio pull request #5
Opened 2021-06-09 22:21 UTC by eroiyo

Add Media Queries
  --A lot of CSS rules have been added in order to be readable also on desktop
  --All the sections have been updated

General improvement of the phone version, now readable on any kind of phone

2021-06-10 01:18 UTC, eroiyo commented
The desktop form has more variables than the mobile version, which is normally impossible in a normal situation, so I stick to the mobile version to avoid problems.

2021-06-10 02:43 UTC, mricanho requested changes
Hi @eroiyo @Ismailco, 

You did good work following the general requirements. 

**First of all, you need to know that you're going to be exposed to this kind of projects your entire career (if you are going to focus on front-end dev), responsiveness it's super important ([check this article](https://digitalnext.co.uk/dn-hub/blog/importance-of-responsive-web-design/) for more info) and yes, most of the times it's full of pain but it gets better and easier when you practice more. When you say "The desktop form has more variables than the mobile version, which is normally impossible in a normal situation", it's actually not impóssible you just need to use more media queries and the right units to make it through**

**But don't worry, we are here to help**

 ## Required Changes ♻️

- [ ] You have some important issues with all the website, and this is mainly because of the units you are using. The viewport-based units are super good in responsiveness but too much of them can cause more troubles than solutions, the same with percentages. The best way to address the responsiveness is with one or two media queries (in this is specific, one media query) and the use of px and a mix of rem and vh. Please use the google chrome developers tools to check the differences in every size of devices, for example:
Form in Mobile (good)

![image](https://user-images.githubusercontent.com/60631456/121454067-ca6eb700-c967-11eb-825b-4fe905170c97.png)

Form in Tablet (Not so good)
![image](https://user-images.githubusercontent.com/60631456/121454163-f0945700-c967-11eb-90ed-ade6468f07a0.png)

Form in Desktop 1024px (Not so good)
![image](https://user-images.githubusercontent.com/60631456/121454318-32250200-c968-11eb-8bb7-e3955433c74e.png)

Form in the original design
![image](https://user-images.githubusercontent.com/60631456/121454434-65679100-c968-11eb-8a27-b945627e8483.png)

- [ ] You have an overflow in your x-axis, the reason must be a width that it's not working as expected, you need to scan all the widths and check the responsible one.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**It must feel like a lot**
![a lot of work](https://user-images.githubusercontent.com/60631456/121456346-8aa9ce80-c96b-11eb-9077-0ce35ea896f4.gif)

**But if you work hard, you are going to have an excellent and professional portfolio to present to futures companies.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 02:43 UTC, mricanho commented on index.html
> +      or a project that
- [ ] You need to have two inputs for the name. One for the first name and the other for the last name, like the original design
![image](https://user-images.githubusercontent.com/60631456/121454942-49b0ba80-c969-11eb-940a-8ece7c34e21d.png)

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  width: 66.01671309192201vw;
- [ ] All these changes are overdoing it. I understand that you want that the width works with both, the mobile version and the desktop version, but you can go back to the 237px (If that size works with the mobile version) and add a `.work-title { width: //new dimension//` in the media query, that's why we use media queries.

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  font-size: 11.1vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  margin-bottom: 1.5vh;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  width: 66.01671309192201vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  font-size: 11.1vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  margin-top: 1.5vh;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
>  }
- [ ] If the visibility is hidden, you don't need to add anything else

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  margin-top: 4.026845637583892vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  padding: 5vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version. And this is especially problematic if the screen goes up to 1024px, check the google chrome developer tools and experiment with the size.

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  font-size: 4vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  line-height: 6vw;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  height: 20vh;
- [ ] Same here, add the new dimension to the media query and let the original dimension for the mobile version

2021-06-10 02:43 UTC, mricanho commented on style.css
> +  }
- [ ] If the visibility is hidden, you don't need to add anything else

2021-06-10 02:43 UTC, mricanho commented on style.css
>  img {
- [ ] You can add another img in the media query or add a new class in the media query that overwrites this one, right now you have a square and it must be more like a rectangle. Check the grid too, maybe the problem is in there.

Your design:
![image](https://user-images.githubusercontent.com/60631456/121456023-ff303d80-c96a-11eb-8b25-444ad8ab1b37.png)

Original design:
![image](https://user-images.githubusercontent.com/60631456/121456062-0fe0b380-c96b-11eb-914c-3ff1df5e25b1.png)

2021-06-10 02:43 UTC, mricanho commented on style.css
>    width: 100%;
- [ ] The margin-top: 40px is too much for the desktop, you can overwrite it in the media query.

2021-06-11 08:18 UTC, DeliceLydia commented on index.html
> +      or a project that
Well addressed this!

2021-06-11 08:30 UTC, DeliceLydia commented on style.css
> +  width: 66.01671309192201vw;
I think for now you fixed this but I can suggest that you reduce a font size of `work-title` in the tablet view

2021-06-11 08:33 UTC, DeliceLydia commented on style.css
> +  font-size: 11.1vw;
- [ ] Please work on the font size to much each device, you can start with mobile, and as you switch the size of the device check how the `font-size` looks and you can change it from the media queries.

2021-06-11 08:35 UTC, DeliceLydia commented on style.css
>  img {
Well done this!

2021-06-11 08:37 UTC, DeliceLydia commented on style.css
>    width: 100%;
Well addressed this on the desktop!

2021-06-11 08:45 UTC, DeliceLydia requested changes
## Hi @eroiyo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, now your desktop view is looking nice,  but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Check how your mobile view looks like because even if this milestone is for desktop we can't approve it when mobile is not yet ready

![pn](https://user-images.githubusercontent.com/44745855/121658377-8e3f7180-caa1-11eb-98b1-1f6eaf8df8e0.png)

please refer to the design and give it some padding or margin to make it look good and to give users the best experience and I suggest that you reduce the font size

### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 09:00 UTC, eroiyo commented
Thanks, I already change the hamburger size, can you check, to see if a nice size?

2021-06-11 10:13 UTC, DeliceLydia approved these changes
# Status: Approved ✔️ 🎉  🎉 
Hi @eroiyo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional
- [ ] You can add padding or margin between your navbar and the first section on a mobile device and be work on the font size to look good on different device

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 10:47 UTC, merged